monitor=,preferred,auto,1

exec-once = waybar
exec-once = dunst
exec-once = /usr/libexec/polkit-kde-authentication-agent-1

$mainMod = SUPER
$terminal = kitty
$menu = rofi -show drun

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, R, exec, $menu

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}
